[package]
name = "amicratered"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.91"

[profile.dev]
opt-level = 3